AUTH_KEY='alhpp&zxM!A_cLydfwAHt!{bRfK)_[&vBnomtndZ?K}5Sh:r]3-2J9q[QadNQ$;q'
SECURE_AUTH_KEY='?]r_TX`PH!<ZU_YKo3i1n}2;YQPKBVCQi@Rc%u|8kdCD#?j%[d/FN-L95@azrLrc'
LOGGED_IN_KEY='}-(@G8)ePCG)@1LPh*Y-TA?rDis,mp;Z,MzQDeiuzXT1$[NdBp8s2~G1927+ib-r'
NONCE_KEY='.0nUczGJ}q^S{/*1Pm;!U+H)XMw0?.+Rd{PkoXYSpMMrw1TEl]Ci`n)T-+p-<-*d'
AUTH_SALT='+n-Z904uLwUf[fS(yJ`v2|LK+{H%-]rRo0i+vgj=ED^NDP4| +nq7c1V2LiqB[[j'
SECURE_AUTH_SALT='W)#RiDm7m6Rj-cYTfPO&d?Pa>]&n8:rGzeL5]Zek|h4@)z:aV-.[[>6:y{2m}cw{'
LOGGED_IN_SALT='#q-<*G+2|}dcwR.gqti+t}g[[KrfW`ez%?K._b+bd#y0g(w.9PWy>.Y=.@|=j|gP'
NONCE_SALT='MZO22r,!91Pd=`K;IN-OO/5J^,KlInJQSYkl 5|J7^@-f1$xk:+]mwLUh%;DwS3D'

#### General Configuration
# worker_processes: Number of NGINX processes. Default = 1
worker_processes = "auto"
worker_rlimit_nofile = 8192

database_name = "wordpress"

#### Events Context Configuration
[events]
# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024


#### HTTP Context Configuration
[http]
# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60


[http.listen]
  port = 80
  bind = "127.0.0.1"