#!/bin/bash

exec 2>&1

{{#if bind.database.first.cfg.local_only ~}}
MYSQL_IP=127.0.0.1
{{else ~}}
MYSQL_IP={{bind.database.first.sys.ip}}
{{/if ~}}

# check if database exists
mysql_ready() {
    mysqladmin ping -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
   echo "waiting for mysql ..."
   exit 1
fi

# create database
mysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{bind.database.first.cfg.username}}"

cp -r {{pkg.path}}/public_html/* {{pkg.svc_data_path}}

if [ ! -f {{pkg.svc_data_path}}/wp-config.php ]; then
    echo "Creating wp-config.php..."
    cp {{pkg.svc_config_path}}/wp-config.php {{pkg.svc_data_path}}/wp-config.php
fi

chmod +x {{pkg.svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}

mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}
